### PR TITLE
Bump component versions

### PR DESCRIPTION
**Pull request by combor**
Update:
- learning locker to v5.1.0
- xapi-service v2.9.9

### CODE REVIEW

**Comment by combor** [comment]
I think the previous version bump to 4.11 is not pushed to docker hub due to missing tags in the repo.

**Comment by jmaupetit** [comment]
Thank you for your feedback @combor! I've added missing release tags (Docker images will be published within the hour).
 
Don't get offended, but I'll close this PR since we are using a script to automate the publication of every release (see `bin/release`). :pray:

**Comment by jmaupetit** [comment]
Closing this in favor to #46

**Comment by jmaupetit** [comment]
@combor learning locker `v5.1.0` and xapi-service `v2.9.9` docker images will available within the hour.

**Comment by combor** [comment]
Thanks!

**Pull request closed without merging**
